language: python
python:
- 2.7
env:
- TOXENV=django18
- TOXENV=django111
matrix:
  include:
  - python: 2.7
    env: TOXENV=quality
  - python: 3.6
    env: TOXENV=py36
before_install:
- export DJANGO_SETTINGS_MODULE=settings
install:
- make install
sudo: false
script:
- make test
after_success: coveralls
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 2.7
    condition: '$TOXENV = django111'
  password:
    secure: oVeS9OrvR5XvJMg86eO004xk9KFh9IbUxWqyWYYFZf1drtrzG2Bm7+F0BgF1hY2l+qyHXinPCCeBmV9CEfav80se1r8K0JFu9MwBHQkvaeBAJV+ItQ2ZumtgNNONoL5VZHIRbEYwl/lbZCWaXpmDLkJSlRVYCECP2bH+RcZkbQM=
